name: hedgehog_lock
description: A new Flutter project.
version: 4.4.1+210
publish_to: none


environment: 
  sdk: '>=3.0.0 <4.0.0'
  # sdk: '>=2.19.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter

##
  firebase_core: ^2.4.1
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  google_sign_in: ^5.0.7
  sign_in_with_apple: ^4.3.0


  get: ^4.6.5
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
  outline_gradient_button: ^2.0.0+1
  intl: ^0.18.0
 
  file_picker: ^5.2.3
  image_picker: ^0.8.6
  camera: ^0.10.0+4
  permission_handler: ^10.2.0
  url_launcher: ^6.1.8
  webview_flutter: ^4.0.2
  purchases_flutter: ^4.8.0
  path_provider: ^2.0.12
  share_plus: ^6.3.0
  get_storage: ^2.0.3
  sleek_circular_slider: 
    git:
      url: https://github.com/dilankayapagit/sleek_circular_slider.git
      ref: master
  
  ##
  water_drop_nav_bar: ^2.2.0+5
  flutter_toggle_tab: ^1.2.0

  #
  open_file_plus: ^3.3.0
  receive_sharing_intent: ^1.4.5
  fluttertoast: ^8.1.3
  toggle_switch: ^2.0.1
  
  
  

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.11.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/newIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21





    
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/extention/
    - assets/images/
    - assets/icon/

  fonts: 
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistRomanRegular.ttf
          weight: 400
